# ##### BEGIN AUTOGENERATED I18N SECTION #####


# NOTE: You can safely move around this auto-generated block (with the begin/end markers!),
#       and edit the translations by hand.
#       Just carefully respect the format of the tuple!

# Tuple of tuples:
# ((msgctxt, msgid), (sources, gen_comments), (lang, translation, (is_fuzzy, comments)), ...)
translations_tuple = (
    (
        ("*", ""),
        ((), ()),
        (
            "ja_JP",
            "MMD Tools Helper 4.0.0 (0)",
            (False, ("FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.",)),
        ),
    ),
    (
        ("Operator", "Add arm IK to MMD model"),
        (
            (
                "bpy.types.MMD_TOOLS_HELPER_OT_add_arm_ik",
                "bpy.types.MMD_TOOLS_HELPER_OT_add_arm_ik",
            ),
            (),
        ),
        ("ja_JP", "腕IKをMMDモデルに追加", (False, ())),
    ),
    (
        ("Operator", "Add leg IK to MMD model"),
        (
            (
                "bpy.types.MMD_TOOLS_HELPER_OT_add_leg_ik",
                "bpy.types.MMD_TOOLS_HELPER_OT_add_leg_ik",
            ),
            (),
        ),
        ("ja_JP", "足IKをMMDモデルに追加", (False, ())),
    ),
    (
        ("Operator", "Armature Diagnostic"),
        (
            (
                "bpy.types.MMD_TOOLS_HELPER_OT_armature_diagnostic",
                "bpy.types.MMD_TOOLS_HELPER_OT_armature_diagnostic",
            ),
            (),
        ),
        ("ja_JP", "アーマチュア診断", (False, ())),
    ),
    (
        ("Operator", "Batch rename bones"),
        (
            (
                "bpy.types.MMD_TOOLS_HELPER_OT_bone_batch_rename",
                "bpy.types.MMD_TOOLS_HELPER_OT_bone_batch_rename",
                "scripts/addons/mmd_tools_helper/panels.py:62",
            ),
            (),
        ),
        ("ja_JP", "ボーン名の一括変更", (False, ())),
    ),
    (
        ("Operator", "Copy Report"),
        (
            (
                "bpy.types.MMD_TOOLS_HELPER_OT_copy_diagnostic_result",
                "bpy.types.MMD_TOOLS_HELPER_OT_copy_diagnostic_result",
                "scripts/addons/mmd_tools_helper/operators/armature_diagnostic.py:160",
            ),
            (),
        ),
        ("ja_JP", "結果をコピー", (False, ())),
    ),
    (
        ("Operator", "Find and replace bone names"),
        (
            (
                "bpy.types.MMD_TOOLS_HELPER_OT_find_replace_bones",
                "bpy.types.MMD_TOOLS_HELPER_OT_find_replace_bones",
            ),
            (),
        ),
        ("ja_JP", "ボーン名の検索と置換", (False, ())),
    ),
    (
        ("Operator", "Miscellaneous Tools"),
        (
            (
                "bpy.types.MMD_TOOLS_HELPER_OT_misc_tools",
                "bpy.types.MMD_TOOLS_HELPER_OT_misc_tools",
            ),
            (),
        ),
        ("ja_JP", "その他ツール", (False, ())),
    ),
    (
        ("Operator", "Convert MMD Camera to Blender"),
        (
            (
                "bpy.types.MMD_TOOLS_HELPER_OT_mmd_camera_to_blender",
                "bpy.types.MMD_TOOLS_HELPER_OT_mmd_camera_to_blender",
            ),
            (),
        ),
        ("ja_JP", "MMDカメラをBlender用に変換", (False, ())),
    ),
    (
        ("Operator", "Convert MMD Toon to Toon Shader"),
        (
            (
                "bpy.types.MMD_TOOLS_HELPER_OT_mmd_toon_shader",
                "bpy.types.MMD_TOOLS_HELPER_OT_mmd_toon_shader",
            ),
            (),
        ),
        ("ja_JP", "MMD Toonをトゥーンシェーダーに変換", (False, ())),
    ),
    (
        ("Operator", "Swap Japanese and English names"),
        (
            (
                "bpy.types.MMD_TOOLS_HELPER_OT_swap_japanese_english",
                "bpy.types.MMD_TOOLS_HELPER_OT_swap_japanese_english",
            ),
            (),
        ),
        ("ja_JP", "日本語名と英語名を入れ替える", (False, ())),
    ),
    (
        ("*", "Add hand and arm IK bones and constraints to active MMD model"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_add_arm_ik",), ()),
        (
            "ja_JP",
            "手と腕のIKボーンとコンストレイントをMMDモデルに追加します",
            (False, ()),
        ),
    ),
    (
        ("*", "Add foot and leg IK bones and constraints to active MMD model"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_add_leg_ik",), ()),
        ("ja_JP", "足のIKボーンとコンストレイントをMMDモデルに追加します", (False, ())),
    ),
    (
        ("*", "Add all bones to diagnosis"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_armature_diagnostic.show_all_bones",), ()),
        ("ja_JP", "全てのボーンを診断する", (False, ())),
    ),
    (
        ("*", "Batch rename bones for armature conversion"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_bone_batch_rename",), ()),
        ("ja_JP", "アーマチュア変換用にボーン名を一括変更します", (False, ())),
    ),
    (
        ("*", "Copy the diagnostic result to the clipboard"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_copy_diagnostic_result",), ()),
        ("ja_JP", "クリップボードに診断結果をコピーします", (False, ())),
    ),
    (
        ("*", "Find and replace strings in bone names"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_find_replace_bones",), ()),
        ("ja_JP", "ボーン名の文字列の検索と置換をします", (False, ())),
    ),
    (
        ("*", "Convert MMD camera to Blender camera"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_mmd_camera_to_blender",), ()),
        ("ja_JP", "MMDカメラをBlender用に変換します", (False, ())),
    ),
    (
        ("*", "Sets up nodes in Blender node editor for rendering toon textures"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_mmd_toon_shader",), ()),
        ("ja_JP", "Toonテクスチャ描画用にノードを組みます", (False, ())),
    ),
    (
        ("*", "Clear existing nodes"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_mmd_toon_shader.clear_node",), ()),
        ("ja_JP", "ノードを除去する", (False, ())),
    ),
    (
        ("*", "Swap Japanese and English names of shape keys, materials, bones"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_swap_japanese_english",), ()),
        (
            "ja_JP",
            "シェイプキー、マテリアル、ボーンの日本語名と英語名を入れ替えます",
            (False, ()),
        ),
    ),
    (
        ("*", "Swap bone names"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_swap_japanese_english.swap_bone",), ()),
        ("ja_JP", "ボーン名を入れ替える", (False, ())),
    ),
    (
        ("*", "Swap material names"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_swap_japanese_english.swap_mat",), ()),
        ("ja_JP", "マテリアル名を入れ替える", (False, ())),
    ),
    (
        ("*", "Swap morph names"),
        (("bpy.types.MMD_TOOLS_HELPER_OT_swap_japanese_english.swap_morph",), ()),
        ("ja_JP", "モーフ名を入れ替える", (False, ())),
    ),
    (
        ("*", "Successfully added arm IK"),
        (("scripts/addons/mmd_tools_helper/operators/add_arm_ik.py:323",), ()),
        ("ja_JP", "腕IKを追加しました", (False, ())),
    ),
    (
        ("*", "Failed to add arm IK: "),
        (("scripts/addons/mmd_tools_helper/operators/add_arm_ik.py:325",), ()),
        ("ja_JP", "腕IKの追加に失敗しました: ", (False, ())),
    ),
    (
        ("*", "Successfully added leg IK"),
        (("scripts/addons/mmd_tools_helper/operators/add_leg_ik.py:395",), ()),
        ("ja_JP", "足IKを追加しました", (False, ())),
    ),
    (
        ("*", "Failed to add leg IK: "),
        (("scripts/addons/mmd_tools_helper/operators/add_leg_ik.py:397",), ()),
        ("ja_JP", "足IKの追加に失敗しました: ", (False, ())),
    ),
    (
        ("*", "Armature diagnosis"),
        (("scripts/addons/mmd_tools_helper/operators/armature_diagnostic.py:157",), ()),
        ("ja_JP", "アーマチュア診断", (False, ())),
    ),
    (
        ("*", "Diagnostic result copied to clipboard"),
        (("scripts/addons/mmd_tools_helper/operators/armature_diagnostic.py:178",), ()),
        ("ja_JP", "クリップボードに診断結果をコピーしました", (False, ())),
    ),
    (
        ("*", "Failed to diagnose armature: "),
        (("scripts/addons/mmd_tools_helper/operators/armature_diagnostic.py:149",), ()),
        ("ja_JP", "アーマチュアの診断に失敗しました: ", (False, ())),
    ),
    (
        ("*", "Failed to batch rename bones: "),
        (("scripts/addons/mmd_tools_helper/operators/batch_bone_rename.py:243",), ()),
        ("ja_JP", "ボーン名の一括変更に失敗しました: ", (False, ())),
    ),
    (
        ("*", "Successfully converted MMD camera"),
        (
            (
                "scripts/addons/mmd_tools_helper/operators/convert_to_blender_camera.py:54",
            ),
            (),
        ),
        ("ja_JP", "MMDカメラを変換しました", (False, ())),
    ),
    (
        ("*", "Failed to convert MMD camera: "),
        (
            (
                "scripts/addons/mmd_tools_helper/operators/convert_to_blender_camera.py:56",
            ),
            (),
        ),
        ("ja_JP", "MMDカメラの変換に失敗しました: ", (False, ())),
    ),
    (
        ("*", "Replaced  entries"),
        (("scripts/addons/mmd_tools_helper/operators/find_replace_bones.py:89",), ()),
        ("ja_JP", "  件置換しました", (False, ())),
    ),
    (
        ("*", "Failed to find and replace bones: "),
        (("scripts/addons/mmd_tools_helper/operators/find_replace_bones.py:91",), ()),
        ("ja_JP", "ボーン名の検索と置換に失敗しました: ", (False, ())),
    ),
    (
        ("*", "Failed to execute misc tools: "),
        (("scripts/addons/mmd_tools_helper/operators/miscellaneous_tools.py:261",), ()),
        ("ja_JP", "その他のツールの実行に失敗しました: ", (False, ())),
    ),
    (
        ("*", "Swapped  names"),
        (
            ("scripts/addons/mmd_tools_helper/operators/swap_japanese_english.py:80",),
            (),
        ),
        ("ja_JP", "  件入れ替えました", (False, ())),
    ),
    (
        ("*", "Failed to swap japanese and english names: "),
        (
            ("scripts/addons/mmd_tools_helper/operators/swap_japanese_english.py:82",),
            (),
        ),
        ("ja_JP", "日本語名と英語名の入れ替えに失敗しました", (False, ())),
    ),
    (
        ("*", "Converted  materials"),
        (("scripts/addons/mmd_tools_helper/operators/toon_tex_to_shader.py:223",), ()),
        ("ja_JP", "マテリアルを  変換しました", (False, ())),
    ),
    (
        ("*", "Failed to add toon shaders: "),
        (("scripts/addons/mmd_tools_helper/operators/toon_tex_to_shader.py:225",), ()),
        ("ja_JP", "トゥーンシェーダーの追加に失敗しました: ", (False, ())),
    ),
    (
        ("*", "IK Makers"),
        (("scripts/addons/mmd_tools_helper/panels.py:29",), ()),
        ("ja_JP", "IK生成", (False, ())),
    ),
    (
        ("Operator", "Add leg IK"),
        (("scripts/addons/mmd_tools_helper/panels.py:31",), ()),
        ("ja_JP", "足IKを追加", (False, ())),
    ),
    (
        ("Operator", "Add arm IK"),
        (("scripts/addons/mmd_tools_helper/panels.py:32",), ()),
        ("ja_JP", "腕IKを追加", (False, ())),
    ),
    (
        ("*", "Armature Diagnostic"),
        (("scripts/addons/mmd_tools_helper/panels.py:35",), ()),
        ("ja_JP", "アーマチュア診断", (False, ())),
    ),
    (
        ("Operator", "Diagnose armature"),
        (("scripts/addons/mmd_tools_helper/panels.py:37",), ()),
        ("ja_JP", "アーマチュアを診断する", (False, ())),
    ),
    (
        ("*", "Replace bone names"),
        (("scripts/addons/mmd_tools_helper/panels.py:52",), ()),
        ("ja_JP", "ボーン名置換", (False, ())),
    ),
    (
        ("Operator", "Find & replace string in bone names"),
        (("scripts/addons/mmd_tools_helper/panels.py:56",), ()),
        ("ja_JP", "ボーン名の文字列の検索と置換", (False, ())),
    ),
    (
        ("*", "Batch rename bones"),
        (("scripts/addons/mmd_tools_helper/panels.py:59",), ()),
        ("ja_JP", "ボーン名の一括変更", (False, ())),
    ),
    (
        ("*", "Swap Japanese & English names"),
        (("scripts/addons/mmd_tools_helper/panels.py:65",), ()),
        ("ja_JP", "日/英入れ替え", (False, ())),
    ),
    (
        ("Operator", "Swap Japanese & English"),
        (("scripts/addons/mmd_tools_helper/panels.py:66",), ()),
        ("ja_JP", "日本語名と英語名を入れ替える", (False, ())),
    ),
    (
        ("*", "MMD Camera to Blender"),
        (("scripts/addons/mmd_tools_helper/panels.py:81",), ()),
        ("ja_JP", "MMDカメラ変換", (False, ())),
    ),
    (
        ("Operator", "Convert MMD Camera"),
        (("scripts/addons/mmd_tools_helper/panels.py:82",), ()),
        ("ja_JP", "MMDカメラを変換", (False, ())),
    ),
    (
        ("*", "MMD Toon to Toon Shader"),
        (("scripts/addons/mmd_tools_helper/panels.py:85",), ()),
        ("ja_JP", "トゥーンシェーダー変換", (False, ())),
    ),
    (
        ("Operator", "Convert to Toon Shader"),
        (("scripts/addons/mmd_tools_helper/panels.py:86",), ()),
        ("ja_JP", "トゥーンシェーダーに変換", (False, ())),
    ),
    (
        ("*", "Miscellaneous Tools"),
        (("scripts/addons/mmd_tools_helper/panels.py:89",), ()),
        ("ja_JP", "その他ツール", (False, ())),
    ),
    (
        ("Operator", "Execute"),
        (("scripts/addons/mmd_tools_helper/panels.py:91",), ()),
        ("ja_JP", "実行", (False, ())),
    ),
    (
        ("*", "MMD Tools Helper"),
        (("Add-on MMD Tools Helper info: name",), ()),
        ("ja_JP", "MMD Tools Helper", (False, ())),
    ),
    (
        ("*", "various helper scripts for MMD Tools"),
        (("Add-on MMD Tools Helper info: description",), ()),
        ("ja_JP", "MMD Tools用の便利なツールセット", (False, ())),
    ),
)

translations_dict = {}
for msg in translations_tuple:
    key = msg[0]
    for lang, trans, (is_fuzzy, comments) in msg[2:]:
        if trans and not is_fuzzy:
            translations_dict.setdefault(lang, {})[key] = trans


# ##### END AUTOGENERATED I18N SECTION #####
