# This file was adapted from [MMD Tools](https://github.com/MMD-Blender/blender_mmd_tools) (GPLv3)

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

name: Addon release

jobs:
  release:
    # Note: `github.event.base_ref` is equal to `refs/heads/main` when the workflow is triggered
    # by a branch, or a lightweight tag (_not_ an annotated tag), placed on the last commit of the `main` branch
    if: github.event.base_ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate zip filename
        run: |
          declare -A tag_prefix_to_blender_version=(
            ["v3"]="bl3.6"
            ["v4"]="bl4.2"
          )
          blender_version=${tag_prefix_to_blender_version[${GITHUB_REF_NAME%%.*}]}
          if [ -z "$blender_version" ]; then
            echo "Error: No Blender version mapping found for tag ${GITHUB_REF_NAME}"
            exit 1
          fi
          echo "zip_filename=mmd_tools_helper-${GITHUB_REF_NAME}-${blender_version}.zip" >> $GITHUB_ENV

      - name: Copy LICENSE file
        run: cp -p LICENSE mmd_tools_helper/

      # - name: Remove development-only files
      #   run: rm -rf mmd_tools_helper/typings

      - name: Create a zip
        run: |
          zip -9r "${{ env.zip_filename }}" mmd_tools_helper/ -x "*/.*" "*/__pycache__/*"

      - name: Create a Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ${{ env.zip_filename }}
          draft: true
          generate_release_notes: true
          prerelease: false
